export const matchRegionMap: Record<string, string> = {
  ME1: "EUROPE",
  BR1: "AMERICAS",
  EUN1: "EUROPE",
  EUW1: "EUROPE",
  JP1: "ASIA",
  KR: "ASIA",
  LA1: "AMERICAS",
  LA2: "AMERICAS",
  NA1: "AMERICAS",
  OC1: "SEA",
  RU: "EUROPE",
  TR1: "EUROPE",
  PH2: "SEA",
  SG2: "SEA",
  TH2: "SEA",
  TW2: "SEA",
  VN2: "SEA",
};
